name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_message:
        description: "Optional description for this deploy"
        required: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # No build step required; site consists of static assets in repository root

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true