name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_message:
        description: "Optional description for this deploy"
        required: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify PAT secret
        run: |
          if [ -z "${{ secrets.GH_PAGES_PAT }}" ]; then
            echo "::error title=Missing PAT::GH_PAGES_PAT secret is not set. Pages deployment aborted."
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
          token: ${{ secrets.GH_PAGES_PAT }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4